# Generated by Django 6.1 on 2026-08-31 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterModel',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='LoginModel',
        ),
    ]
